import { Card } from "../../../interfaces";
import Set from "../Fantastical Parade";
const card: Card = {
    set: Set,
    image: {
        de: "https://game.pokemontcgpocket.app/de/tcgp/B2/057",
        es: "https://game.pokemontcgpocket.app/es/tcgp/B2/057",
        fr: "https://game.pokemontcgpocket.app/fr/tcgp/B2/057",
        it: "https://game.pokemontcgpocket.app/it/tcgp/B2/057",
        "zh-tw": "https://game.pokemontcgpocket.app/zh-tw/tcgp/B2/057"
    },
    name: {
        en: "Bellibolt",
        "fr": "Bellibolt",
        "es": "Bellibolt",
        "it": "Bellibolt",
        "de": "Bellibolt",
        "pt-br": "Bellibolt",
        "zh-tw": "貝利博爾特"
    },
    illustrator: "Oswaldo KATO",
    rarity: "Two Diamond",
    category: "Pokemon",
    hp: 130,
    types: ["Lightning"],
    evolveFrom: {
        en: "Tadbulb",
        "fr": "Tadbulbe",
        "es": "renacuajo",
        "it": "Tadbulb",
        "de": "Kaulzwiebel",
        "pt-br": "Tabulbo",
        "zh-tw": "塔德燈泡"
    },
    description: {
        en: "What appear to be eyeballs are actually organs\nfor discharging the electricity generated by\nBellibolt's belly-button dynamo.",
        "fr": "Ce qui semble être des globes oculaires est en réalité des organes\npour évacuer l'électricité produite par\nLa dynamo du nombril de Bellibolt.",
        "es": "Lo que parecen ser globos oculares son en realidad órganos.\npara descargar la electricidad generada por\nLa dinamo del ombligo de Bellibolt.",
        "it": "Quelli che sembrano bulbi oculari sono in realtà organi\nper scaricare l'elettricità generata da\nLa dinamo dell'ombelico di Bellibolt.",
        "de": "Was wie Augäpfel aussieht, sind in Wirklichkeit Organe\nzum Abführen des erzeugten Stroms\nBellibolts Bauchnabeldynamo.",
        "pt-br": "O que parecem ser globos oculares são na verdade órgãos\npara descarregar a eletricidade gerada por\nO dínamo do umbigo de Bellibolt.",
        "zh-tw": "看似眼球的東西實際上是器官\n用於釋放所產生的電力\n貝利博爾特的肚臍發電機。"
    },
    stage: "Stage1",
    attacks: [{
            name: {
                en: "Electric Ball",
                "fr": "Boule électrique",
                "es": "Bola eléctrica",
                "it": "Palla elettrica",
                "de": "Elektrischer Ball",
                "pt-br": "Bola Elétrica",
                "zh-tw": "電動球"
            },
            damage: 80,
            cost: ["Lightning", "Lightning", "Colorless"]
        }],
    weaknesses: [{
            type: "Fighting",
            value: "+20"
        }],
    retreat: 3
};
export default card;
