import { Card } from "../../../interfaces";
import Set from "../Paldean Wonders";
const card: Card = {
    set: Set,
    image: {
        de: "https://game.pokemontcgpocket.app/de/tcgp/B2a/044",
        en: "https://game.pokemontcgpocket.app/en/tcgp/B2a/044",
        es: "https://game.pokemontcgpocket.app/es/tcgp/B2a/044",
        fr: "https://game.pokemontcgpocket.app/fr/tcgp/B2a/044",
        it: "https://game.pokemontcgpocket.app/it/tcgp/B2a/044",
        "zh-tw": "https://game.pokemontcgpocket.app/zh-tw/tcgp/B2a/044",
        "pt-br": "https://game.pokemontcgpocket.app/pt/tcgp/B2a/044"
    },
    name: {
        en: "Kilowattrel",
        fr: "Fulgulairo",
        es: "Kilowattrel",
        it: "Kilowattrel",
        de: "Voltrean",
        "pt-br": "Kilowattrel",
        "zh-tw": "大電海燕",
        pt: "Kilowattrel"
    },
    illustrator: "Pani Kobayashi",
    rarity: "Two Diamond",
    category: "Pokemon",
    hp: 90,
    types: ["Lightning"],
    dexId: [941],
    evolveFrom: {
        en: "Wattrel",
        fr: "Zapétrel",
        es: "Wattrel",
        it: "Wattrel",
        de: "Voltrel",
        "pt-br": "Wattrel",
        "zh-tw": "電海燕",
        pt: "Wattrel"
    },
    description: {
        en: "It uses its throat sac to store electricity generated by its wings. There's hardly any oil in its feathers, so it is a poor swimmer.",
        "fr": "Il utilise son sac pharyngé pour stocker l'électricité générée par ses ailes. Il n'y a pratiquement pas d'huile dans ses plumes, c'est donc un mauvais nageur.",
        "es": "Utiliza el saco de su garganta para almacenar la electricidad generada por sus alas. Apenas tiene aceite en sus plumas, por lo que no es un buen nadador.",
        "it": "Usa la sacca della gola per immagazzinare l'elettricità generata dalle sue ali. Non c'è quasi olio nelle sue piume, quindi è un pessimo nuotatore.",
        "de": "Es nutzt seinen Kehlsack, um die von seinen Flügeln erzeugte Elektrizität zu speichern. Da es kaum Öl in seinen Federn hat, ist es ein schlechter Schwimmer.",
        "pt-br": "Ele usa seu saco na garganta para armazenar a eletricidade gerada por suas asas. Quase não há óleo em suas penas, então ele é um péssimo nadador.",
        "zh-tw": "它利用喉囊來儲存翅膀產生的電力。它的羽毛中幾乎沒有油脂，所以它的游泳能力很差。"
    },
    stage: "Stage1",
    attacks: [
        {
            name: {
                en: "Speed Wing",
                fr: "Ailes Vives",
                es: "Ala Veloz",
                it: "Alaveloce",
                de: "Turboschwinge",
                "pt-br": "Asa de velocidade",
                "zh-tw": "速度之翼",
                'es-mx': "Ala Veloz",
                pt: "Asa da Velocidade"
            },
            damage: "40",
            cost: ["Lightning"],
        },
    ],
    weaknesses: [
        {
            type: "Lightning",
            value: "+20",
        },
    ],
    retreat: 0
};
export default card;
